sudo: required
notifications:
  email: false
services:
- docker
language: python
python:
- 3.6
git:
  depth: false
script:
- make docker-build
- make docker-push
deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis-deploy.sh
  on:
    branch: master
env:
  global:
  - secure: tIj5p47xa7v3Z8jZNBwBbbEsZrQCeUbwKdHnmpjykUx9LlEag6Row5Ijy5Xb/WR8bQNPNefy4NLMO7PTPG+9hSb8TC7DxF1kl6SMewsZ8DqNVjHGoJxWYH8qUwqlBL5M6CwlSILjoDX0n1HRMbY8a+EztE9D6wKwhYT4ctlekqIlkPA+zpCdW+xCISeNFmcyesRhjPtEwlkGmZ53b8MAss1vieHBfchYHqpIOjbH8VgvQXmlUkxdG+O7T+fDr7OyOUy95y1IVGNtm3nHCb/CzYG9m51IN8O44EqHNoFk/xxAKDZpVcE8pfCvFn9ml0erBqbozl333bo7X17KHCh0HvcNx33h+77xmhamlJoeVR/Lznx0XAe5yGgsgBjWgmFn01YPBPSO5H9UFbAP49IY1sI17o+D9SFE76JRvXQkGGizNnoKs29X6CPm3TFJFN/sh6IMT0p+Rti7u0EraytbheBx/5EvHcPx5uHKgG/rWHeVa0ZZVO43aNL+UbXpWtNWiNZm/pUYxFrgyxoJTanEONFHyVDFAa89FOPbvGPTSWLiuspwc2DM08/d4XDzhDfNWa09gxoqI+FQVMnmilk0AKJKf4QDGjcE/STpHl+eoirRgGXGSkQFkUh5DKHTMVsikOjjbatifAcBquPvh71L4iJJhftCYxPQV4I+ciOr31A=
  - secure: loCNNgWLtH2l5wEQdZk/iN7O9MQVyNAXCxXV1W5/MwZqts+mV1n9G7gZiDKSnFJTuSYbQiq5D7+9GHUSLFC4IYqIq1T8rqgvb7vIDNTX5+qtvtRgDGTh1J7ZhpRhCRj4LNPAYVpQyEptRPTY7Q9uAM55olbK1XlaHVhzF28rtVgP34b2+Uy0IlhhD1wrMvY4kbo/R94QLV3jL70vTz6xoonZv3TsJgdVmGltaFDgE6WF0bsn/KAbtjcTmxqyIIuHliYKtf8xeoKTHRoArHHzh99+Xyn1tkOGcG91XBgxSqpRDuxtVO0Zuw+MITCP57Q0LqGAfwMm9Hsgof6lNqIoeWUuDALtm25HTzSNwdZshbwhdcpdlgYhyJCT3IO1+moippyfoi90ZNe1rMXfhlK48OwIgSZcVIjv/GQyO0KjiTkzF2A3VszjorYuOh+RLhdxPVHTcJGtQPG04bDrZLL394Oy3YD0DFFlVso74YzORB5PeiFQu+06T7JJB4YgjGyG5CImek4Plu+O7qnaEVGE2LNDcqLAKU/umEkoNIp20FdD7j+GIkX8w5eDhk28Ir414+9XE9SmvCKqWtNLsySTx3V050/0YDIMbWOgxIZb1bf0v/2kknHrqHXWws5KgU6ABt1D5dvE1bKhJrQ+bGiixU2QJ8AKZiM0NECBut8Amyg=
